apiVersion: v1
kind: ConfigMap
metadata:
  name: rmshop-config
  namespace: rmshop
data:
  config.yaml: |
    server:
      port: "8080"
    db:
      host: "postgres"
      port: "5432"
      user: "postgres"
      password: "postgres"
      name: "rmshop_db"
      sslmode: "disable"
