apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmshop
  namespace: rmshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmshop
  template:
    metadata:
      labels:
        app: rmshop
    spec:
      containers:
      - name: rmshop
        image: mohamedfawas/rmshop:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        # Database Configuration
        - name: DB_HOST
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
        - name: DB_NAME
          value: "rmshop_db"
        - name: DB_SSLMODE
          value: "disable"
        # Cloudinary Configuration
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: cloudinary_cloud_name
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: cloudinary_api_key
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: cloudinary_api_secret
        # JWT Configuration
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: jwt_secret
        # SMTP Configuration
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: smtp_username
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: smtp_password
        # Razorpay Configuration
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: razorpay_key_id
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              name: rmshop-secrets
              key: razorpay_key_secret
