apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "3"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"rmshop","namespace":"rmshop"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"rmshop"}},"template":{"metadata":{"labels":{"app":"rmshop"}},"spec":{"containers":[{"env":[{"name":"SERVER_PORT","value":"8080"},{"name":"DB_HOST","value":"postgres"},{"name":"DB_PORT","value":"5432"},{"name":"DB_USER","valueFrom":{"secretKeyRef":{"key":"username","name":"db-credentials"}}},{"name":"DB_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"db-credentials"}}},{"name":"DB_NAME","value":"rmshop_db"},{"name":"ADMIN_USERNAME","valueFrom":{"secretKeyRef":{"key":"admin_username","name":"rmshop-secrets"}}},{"name":"ADMIN_PASSWORD","valueFrom":{"secretKeyRef":{"key":"admin_password","name":"rmshop-secrets"}}},{"name":"SMTP_HOST","value":"smtp.gmail.com"},{"name":"SMTP_PORT","value":"587"},{"name":"SMTP_USERNAME","valueFrom":{"secretKeyRef":{"key":"smtp_username","name":"rmshop-secrets"}}},{"name":"SMTP_PASSWORD","valueFrom":{"secretKeyRef":{"key":"smtp_password","name":"rmshop-secrets"}}},{"name":"CLOUDINARY_CLOUD_NAME","valueFrom":{"secretKeyRef":{"key":"cloudinary_cloud_name","name":"rmshop-secrets"}}},{"name":"CLOUDINARY_API_KEY","valueFrom":{"secretKeyRef":{"key":"cloudinary_api_key","name":"rmshop-secrets"}}},{"name":"CLOUDINARY_API_SECRET","valueFrom":{"secretKeyRef":{"key":"cloudinary_api_secret","name":"rmshop-secrets"}}},{"name":"JWT_SECRET","valueFrom":{"secretKeyRef":{"key":"jwt_secret","name":"rmshop-secrets"}}},{"name":"RAZORPAY_KEY_ID","valueFrom":{"secretKeyRef":{"key":"razorpay_key_id","name":"rmshop-secrets"}}},{"name":"RAZORPAY_KEY_SECRET","valueFrom":{"secretKeyRef":{"key":"razorpay_key_secret","name":"rmshop-secrets"}}}],"image":"mohamedfawas/rmshop:latest","imagePullPolicy":"Always","livenessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":30,"periodSeconds":20},"name":"rmshop","ports":[{"containerPort":8080}],"readinessProbe":{"httpGet":{"path":"/health","port":8080},"initialDelaySeconds":15,"periodSeconds":10}}]}}}}
  creationTimestamp: "2024-12-22T06:22:09Z"
  generation: 5
  name: rmshop
  namespace: rmshop
  resourceVersion: "44720"
  uid: 7312d1f6-de85-43c3-a036-2f00fc5ab62d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rmshop
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rmshop
    spec:
      containers:
      - env:
        - name: SERVER_PORT
          value: "8080"
        - name: DB_HOST
          value: postgres
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: db-credentials
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: db-credentials
        - name: DB_NAME
          value: rmshop_db
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              key: admin_username
              name: rmshop-secrets
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              key: admin_password
              name: rmshop-secrets
        - name: SMTP_HOST
          value: smtp.gmail.com
        - name: SMTP_PORT
          value: "587"
        - name: SMTP_USERNAME
          valueFrom:
            secretKeyRef:
              key: smtp_username
              name: rmshop-secrets
        - name: SMTP_PASSWORD
          valueFrom:
            secretKeyRef:
              key: smtp_password
              name: rmshop-secrets
        - name: CLOUDINARY_CLOUD_NAME
          valueFrom:
            secretKeyRef:
              key: cloudinary_cloud_name
              name: rmshop-secrets
        - name: CLOUDINARY_API_KEY
          valueFrom:
            secretKeyRef:
              key: cloudinary_api_key
              name: rmshop-secrets
        - name: CLOUDINARY_API_SECRET
          valueFrom:
            secretKeyRef:
              key: cloudinary_api_secret
              name: rmshop-secrets
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              key: jwt_secret
              name: rmshop-secrets
        - name: RAZORPAY_KEY_ID
          valueFrom:
            secretKeyRef:
              key: razorpay_key_id
              name: rmshop-secrets
        - name: RAZORPAY_KEY_SECRET
          valueFrom:
            secretKeyRef:
              key: razorpay_key_secret
              name: rmshop-secrets
        image: mohamedfawas/rmshop:latest
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        name: rmshop
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 15
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2024-12-28T03:11:24Z"
    lastUpdateTime: "2024-12-28T03:11:32Z"
    message: ReplicaSet "rmshop-5646c7784f" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2024-12-28T03:11:37Z"
    lastUpdateTime: "2024-12-28T03:11:37Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 5
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
