apiVersion: v1
kind: Service
metadata:
  name: rmshop
  namespace: rmshop
  labels:
    app: rmshop
spec:
  selector:
    app: rmshop
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmshop
  namespace: rmshop
  labels:
    app: rmshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmshop
  template:
    metadata:
      labels:
        app: rmshop
    spec:
      containers:
      - name: rmshop
        image: mohamedfawas/rmshop:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        env:
          # Server Configuration
          - name: SERVER_PORT
            value: "8080"
          
          # Database Configuration
          - name: DB_HOST
            value: "postgres"
          - name: DB_PORT
            value: "5432"
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: db_password
          - name: DB_NAME
            value: "rmshop_db"
          
          # Admin Configuration
          - name: ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: admin_username
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: admin_password
          
          # SMTP Configuration
          - name: SMTP_HOST
            value: "smtp.gmail.com"
          - name: SMTP_PORT
            value: "587"
          - name: SMTP_USERNAME
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: smtp_username
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: smtp_password
          
          # Cloudinary Configuration
          - name: CLOUDINARY_CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: cloudinary_cloud_name
          - name: CLOUDINARY_API_KEY
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: cloudinary_api_key
          - name: CLOUDINARY_API_SECRET
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: cloudinary_api_secret
          
          # JWT Configuration
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: jwt_secret
          
          # Razorpay Configuration
          - name: RAZORPAY_KEY_ID
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: razorpay_key_id
          - name: RAZORPAY_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: rmshop-secrets
                key: razorpay_key_secret
        
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"